#include "mesh_exporter.h"
#include <iostream>
#include <iomanip>

namespace p0::vehicle {

bool MeshExporter::ExportOBJ(const MeshData& mesh, const std::string& filename) {
    std::ofstream file(filename);
    if (!file.is_open()) {
        std::cerr << "Failed to open file: " << filename << "\n";
        return false;
    }

    file << "# X-Racing Vehicle Mesh\n";
    file << "# Generated by VehicleGenerator\n";
    file << "o Vehicle\n";
    file << std::fixed << std::setprecision(6);

    // Write vertices
    for (const auto& v : mesh.vertices) {
        double x = v[0];
        double y = v[1];
        double z = v[2];
        file << "v " << x << " " << y << " " << z << "\n";
    }

    // Write normals
    for (const auto& n : mesh.normals) {
        double nx = n[0];
        double ny = n[1];
        double nz = n[2];
        file << "vn " << nx << " " << ny << " " << nz << "\n";
    }

    // Write UVs
    for (const auto& uv : mesh.uvs) {
        double u = uv[0];
        double v = uv[1];
        file << "vt " << u << " " << v << "\n";
    }

    // Write faces (OBJ indices are 1-based)
    for (size_t i = 0; i < mesh.indices.size(); i += 3) {
        int i0 = mesh.indices[i] + 1;
        int i1 = mesh.indices[i + 1] + 1;
        int i2 = mesh.indices[i + 2] + 1;

        file << "f "
             << i0 << "/" << i0 << "/" << i0 << " "
             << i1 << "/" << i1 << "/" << i1 << " "
             << i2 << "/" << i2 << "/" << i2 << "\n";
    }

    file.close();
    std::cout << "Exported mesh to: " << filename << "\n";
    std::cout << "  Vertices: " << mesh.vertices.size() << "\n";
    std::cout << "  Triangles: " << mesh.indices.size() / 3 << "\n";

    return true;
}

bool MeshExporter::ExportCarOBJ(const VehicleGeometry& geo, const std::string& filename) {
    MeshData car = VehicleGenerator::GenerateCar(geo);
    return ExportOBJ(car, filename);
}

} // namespace p0::vehicle
