// X-Racing — OBJ mesh exporter implementation
// Author: alessio
#include "mesh_exporter.h"
#include <iostream>
#include <sstream>

// Project 0 — OBJ mesh exporter implementation
// Writes vertices, normals, UVs and triangular faces in Wavefront format.
namespace p0::vehicle {

// Export a MeshData to a Wavefront OBJ file.
// OBJ uses 1-based indices; this writer converts from 0-based internal indices.
// Vertex colors are written as additional RGB values after xyz if present.
// Faces are written in v/vt/vn format (all indices equal for flat arrays).
bool MeshExporter::ExportOBJ(const MeshData& mesh, const std::string& filename) {
    std::ofstream file(filename);
    if (!file.is_open()) {
        std::cerr << "Failed to open file: " << filename << "\n";
        return false;
    }

    file << "# X-Racing Vehicle Mesh\n";
    file << "# Generated by VehicleGenerator\n";
    file << "o Vehicle\n";

    // Write vertex positions (v x y z [r g b]).
    bool has_colors = !mesh.colors.empty() && mesh.colors.size() == mesh.vertices.size();
    for (size_t i = 0; i < mesh.vertices.size(); ++i) {
        const auto& v = mesh.vertices[i];
        file << "v " << v[0] << " " << v[1] << " " << v[2];
        if (has_colors) {
            const auto& c = mesh.colors[i];
            file << " " << c[0] << " " << c[1] << " " << c[2];
        }
        file << "\n";
    }

    // Write vertex normals (vn x y z).
    for (const auto& n : mesh.normals) {
        file << "vn " << n[0] << " " << n[1] << " " << n[2] << "\n";
    }

    // Write texture coordinates (vt u v).
    for (const auto& uv : mesh.uvs) {
        file << "vt " << uv[0] << " " << uv[1] << "\n";
    }

    // Write triangular faces (f i0 i1 i2) with 1-based indices.
    for (size_t i = 0; i < mesh.indices.size(); i += 3) {
        int i0 = mesh.indices[i] + 1;
        int i1 = mesh.indices[i + 1] + 1;
        int i2 = mesh.indices[i + 2] + 1;
        file << "f " << i0 << "/" << i0 << "/" << i0 << " "
             << i1 << "/" << i1 << "/" << i1 << " "
             << i2 << "/" << i2 << "/" << i2 << "\n";
    }

    file.close();
    std::cout << "Exported mesh to: " << filename << "\n";
    std::cout << "  Vertices: " << mesh.vertices.size() << "\n";
    std::cout << "  Triangles: " << mesh.indices.size() / 3 << "\n";

    return true;
}

// Generate a complete car mesh from geometry parameters and export it to OBJ.
// Convenience function combining mesh generation and file I/O.
bool MeshExporter::ExportCarOBJ(const VehicleGeometry& geo, const std::string& filename) {
    MeshData car = VehicleGenerator::GenerateCar(geo);
    return ExportOBJ(car, filename);
}

} // namespace p0::vehicle
